# Build settings
permalink: /projects/:title/
markdown: kramdown
highlighter: pygments
plugins: [jekyll-paginate-v2]

pagination:
  enabled: true
  per_page: 3
  permalink: "/page/:num/"

comments: true

source: source
destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: webpage
description: "A free Jekyll theme for download"
keywords: "Jekyll, theme, free, download, SEO, blog, web"
url: http://shuifanzz.github.io
baseurl: "/webpage"

google_analytics: UA-52446115-1
repo: http://github.com/ShuiFanZZ/webpage
disqus_shortname: "shuifanzz"
disqus_site_shortname: "shuifanzz"

# Author settings
author:
  name: Zezhong Pan
  job: Machine Learning and Software Engineer
  bio: "A passionate and quick learner, always looking for the best project and good coffee."
  thumb: /images/author.jpg
  email: zezhongpan@gmail.com
  url: https://shuifanzz.github.io/webpage
  github: https://github.com/ShuiFanZZ
  twitter: 
  facebook: 
  linkedin: https://linkedin.com/in/zezhongpan

# navbar pages
navbar:
  - slug: about
    title: About
  # - slug: icons
  #   title: Icons
  - slug: projects
    title: Projects

exclude: ["config.rb", "src", "Gemfile", "Gemfile.lock", "package.json","README.md", "Rakefile"]
